[package]
name = "activity_duration"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, optional = true }

[dev-dependencies]

[features]
default = []
serde = [ "dep:serde" ]

[lints]
workspace = true
